create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  weight text not null default '250 g',
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id boolean primary key default true,
  name text not null default 'DonCafé',
  logo_url text,
  banner_url text,
  whatsapp text,
  email text,
  address text,
  social_links jsonb not null default '{}'::jsonb,
  opening_hours text,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  nombre_cliente text not null,
  telefono text not null,
  correo text,
  direccion text not null,
  ciudad text not null,
  notas text,
  metodo_pago text not null check (metodo_pago in ('Nequi', 'Efectivo contra entrega')),
  estado text not null default 'Pendiente',
  subtotal numeric(12,2) not null,
  costo_envio numeric(12,2) not null default 0,
  total numeric(12,2) not null,
  comprobante_pago text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists nombre_cliente text;
alter table public.orders add column if not exists telefono text;
alter table public.orders add column if not exists correo text;
alter table public.orders add column if not exists direccion text;
alter table public.orders add column if not exists ciudad text;
alter table public.orders add column if not exists notas text;
alter table public.orders add column if not exists metodo_pago text;
alter table public.orders add column if not exists estado text default 'Pendiente';
alter table public.orders add column if not exists subtotal numeric(12,2) default 0;
alter table public.orders add column if not exists costo_envio numeric(12,2) default 0;
alter table public.orders add column if not exists total numeric(12,2) default 0;
alter table public.orders add column if not exists comprobante_pago text;
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.orders(id) on delete cascade,
  producto_id text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null,
  subtotal numeric(12,2) not null
);

alter table public.order_items add column if not exists pedido_id bigint;
alter table public.order_items add column if not exists producto_id text;
alter table public.order_items add column if not exists cantidad integer;
alter table public.order_items add column if not exists precio_unitario numeric(12,2);
alter table public.order_items add column if not exists subtotal numeric(12,2);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

alter table public.products enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "public can read active products" on public.products;
create policy "public can read active products" on public.products for select to anon, authenticated using (active = true);
drop policy if exists "admins can manage products" on public.products;
create policy "admins can manage products" on public.products for all to authenticated using (true) with check (true);
drop policy if exists "public can read store settings" on public.store_settings;
create policy "public can read store settings" on public.store_settings for select to anon, authenticated using (true);
drop policy if exists "admins can manage store settings" on public.store_settings;
create policy "admins can manage store settings" on public.store_settings for all to authenticated using (true) with check (true);

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders" on public.orders for insert to anon, authenticated with check (true);
drop policy if exists "public can create order items" on public.order_items;
create policy "public can create order items" on public.order_items for insert to anon, authenticated with check (true);
drop policy if exists "admins can read orders" on public.orders;
create policy "admins can read orders" on public.orders for select to authenticated using (true);
drop policy if exists "admins can update orders" on public.orders;
create policy "admins can update orders" on public.orders for update to authenticated using (true) with check (true);
drop policy if exists "admins can read order items" on public.order_items;
create policy "admins can read order items" on public.order_items for select to authenticated using (true);

create or replace function public.create_order(order_data jsonb, order_items jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  item jsonb;
begin
  insert into public.orders (
    nombre_cliente, telefono, correo, direccion, ciudad, notas,
    metodo_pago, estado, subtotal, costo_envio, total
  ) values (
    order_data->>'nombre_cliente', order_data->>'telefono', order_data->>'correo',
    order_data->>'direccion', order_data->>'ciudad', order_data->>'notas',
    order_data->>'metodo_pago', order_data->>'estado',
    (order_data->>'subtotal')::numeric, (order_data->>'costo_envio')::numeric,
    (order_data->>'total')::numeric
  ) returning id into new_order_id;

  for item in select * from jsonb_array_elements(order_items) loop
    insert into public.order_items (pedido_id, producto_id, cantidad, precio_unitario, subtotal)
    values (
      new_order_id, item->>'producto_id', (item->>'cantidad')::integer,
      (item->>'precio_unitario')::numeric, (item->>'subtotal')::numeric
    );
  end loop;
  return new_order_id;
end;
$$;

grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('payment-receipts', 'payment-receipts', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "customers can upload payment receipts" on storage.objects;
create policy "customers can upload payment receipts" on storage.objects for insert to anon, authenticated
with check (bucket_id = 'payment-receipts');
drop policy if exists "admins can read payment receipts" on storage.objects;
create policy "admins can read payment receipts" on storage.objects for select to authenticated
using (bucket_id = 'payment-receipts');

drop policy if exists "public can read product images" on storage.objects;
create policy "public can read product images" on storage.objects for select to anon, authenticated
using (bucket_id = 'product-images');
drop policy if exists "admins can manage product images" on storage.objects;
create policy "admins can manage product images" on storage.objects for all to authenticated
using (bucket_id = 'product-images') with check (bucket_id = 'product-images');
