import { CheckCircle2, Clipboard, CreditCard, MapPin, PackageCheck, Store } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { formatCurrency } from "../context/CartContext";

type ConfirmationState = { orderId?: string; total?: number; payment?: "nequi" | "cash"; status?: string };

export default function Confirmation() {
  const { state } = useLocation();
  const order = (state ?? {}) as ConfirmationState;
  const [copied, setCopied] = useState(false);
  const orderNumber = order.orderId ? `#ORD-${order.orderId.slice(-6).padStart(6, "0")}` : "#ORD-PENDIENTE";
  async function copyOrder() { await navigator.clipboard.writeText(orderNumber); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  return <main className="min-h-screen bg-[#312117] px-5 py-8 text-white sm:py-14"><header className="mx-auto flex max-w-5xl items-center justify-between"><Link to="/" className="flex items-center gap-2 font-serif text-lg text-[#d4a55d]"><Store size={18} /> DONCAFÉ</Link><span className="text-[10px] uppercase tracking-widest text-[#c6b4a6]">Pedido recibido</span></header><section className="mx-auto mt-12 max-w-2xl rounded-2xl border border-[#594333] bg-[#211712] p-7 shadow-2xl sm:p-12"><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#e6f0df] text-[#416d2b]"><CheckCircle2 size={34} /></div><h1 className="mt-7 font-serif text-4xl">Gracias por tu compra</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#c6b4a6]">Recibimos tu pedido y prepararemos tu selección de café artesanal con el mayor cuidado.</p></div><div className="mt-9 flex items-center justify-between rounded-lg border border-[#594333] bg-[#2a1c15] p-4"><div><span className="block text-[9px] uppercase tracking-widest text-[#a98f7d]">Número de orden</span><strong className="mt-1 block font-mono text-lg text-[#f3dfbd]">{orderNumber}</strong></div><button onClick={copyOrder} className="flex items-center gap-1.5 text-[10px] text-[#d4a55d]"><Clipboard size={14} /> {copied ? "Copiado" : "Copiar"}</button></div><div className="mt-7 grid gap-5 border-b border-[#594333] pb-7 sm:grid-cols-2"><div className="flex gap-3"><CreditCard size={17} className="text-[#d4a55d]" /><div><span className="block text-[9px] uppercase tracking-widest text-[#a98f7d]">Método de pago</span><strong className="mt-1 block text-sm">{order.payment === "cash" ? "Efectivo contra entrega" : "Nequi"}</strong></div></div><div className="flex gap-3"><MapPin size={17} className="text-[#d4a55d]" /><div><span className="block text-[9px] uppercase tracking-widest text-[#a98f7d]">Estado</span><strong className="mt-1 block text-sm text-[#b4da8d]">{order.status ?? "Pendiente"}</strong></div></div></div><div className="mt-7 flex items-center justify-between"><div className="flex items-center gap-3"><PackageCheck className="text-[#b4da8d]" size={22} /><span className="text-xs text-[#c6b4a6]">Total del pedido</span></div><strong className="font-serif text-2xl text-[#d4a55d]">{formatCurrency(order.total ?? 0)}</strong></div><p className="mt-7 rounded-lg border border-[#49352a] bg-[#2a1c15] p-4 text-center text-xs leading-5 text-[#c6b4a6]">{order.payment === "cash" ? "Pagarás en efectivo al momento de recibir tu pedido." : "Una vez verifiquemos el pago, comenzaremos el tostado y empaque. Te avisaremos cuando tu pedido avance."}</p><Link to="/" className="mx-auto mt-7 flex w-fit items-center gap-2 rounded-lg border border-[#b8892d] px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-[#d4a55d] hover:bg-[#b8892d] hover:text-[#211712]">Volver a la tienda</Link></section></main>;
}
